# 商品推薦

## 下載資料集

In [ ]:
# 在colab中可以用這個
!wget https://archive.ics.uci.edu/ml/machine-learning-databases/00352/Online%20Retail.xlsx

--2020-10-28 05:38:12--  https://archive.ics.uci.edu/ml/machine-learning-databases/00352/Online%20Retail.xlsx
Resolving archive.ics.uci.edu (archive.ics.uci.edu)... 128.195.10.252
Connecting to archive.ics.uci.edu (archive.ics.uci.edu)|128.195.10.252|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 23715344 (23M) [application/x-httpd-php]
Saving to: ‘Online Retail.xlsx’

Online Retail.xlsx  100%[===================>]  22.62M  23.4MB/s    in 1.0s

2020-10-28 05:38:13 (23.4 MB/s) - ‘Online Retail.xlsx’ saved [23715344/23715344]

## 讀取資料集

In [ ]:
import pandas as pd

In [ ]:
df = pd.read_excel('Online Retail.xlsx')

In [ ]:
df.shape

(541909, 8)

In [ ]:
df.head()

  InvoiceNo StockCode  ... CustomerID         Country
0    536365    85123A  ...    17850.0  United Kingdom
1    536365     71053  ...    17850.0  United Kingdom
2    536365    84406B  ...    17850.0  United Kingdom
3    536365    84029G  ...    17850.0  United Kingdom
4    536365    84029E  ...    17850.0  United Kingdom

[5 rows x 8 columns]

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 541909 entries, 0 to 541908
Data columns (total 8 columns):
 #   Column       Non-Null Count   Dtype
---  ------       --------------   -----
 0   InvoiceNo    541909 non-null  object
 1   StockCode    541909 non-null  object
 2   Description  540455 non-null  object
 3   Quantity     541909 non-null  int64
 4   InvoiceDate  541909 non-null  datetime64[ns]
 5   UnitPrice    541909 non-null  float64
 6   CustomerID   406829 non-null  float64
 7   Country      541909 non-null  object
dtypes: datetime64[ns](1), float64(2), int64(1), object(4)
memory usage: 33.1+ MB

In [ ]:
len(df.loc[df['Quantity'] <= 0])

10624

In [ ]:
df.loc[df['Quantity'] <= 0].head()

    InvoiceNo StockCode  ... CustomerID         Country
141   C536379         D  ...    14527.0  United Kingdom
154   C536383    35004C  ...    15311.0  United Kingdom
235   C536391     22556  ...    17548.0  United Kingdom
236   C536391     21984  ...    17548.0  United Kingdom
237   C536391     21983  ...    17548.0  United Kingdom

[5 rows x 8 columns]

In [ ]:
# 只取 quantity > 0 的資料來做分析
df = df.loc[df['Quantity'] > 0]

## 缺失值處理

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 531285 entries, 0 to 541908
Data columns (total 8 columns):
 #   Column       Non-Null Count   Dtype
---  ------       --------------   -----
 0   InvoiceNo    531285 non-null  object
 1   StockCode    531285 non-null  object
 2   Description  530693 non-null  object
 3   Quantity     531285 non-null  int64
 4   InvoiceDate  531285 non-null  datetime64[ns]
 5   UnitPrice    531285 non-null  float64
 6   CustomerID   397924 non-null  float64
 7   Country      531285 non-null  object
dtypes: datetime64[ns](1), float64(2), int64(1), object(4)
memory usage: 36.5+ MB

In [ ]:
df['CustomerID'].isna().sum()

133361

In [ ]:
df['CustomerID'].isna().head()

0    False
1    False
2    False
3    False
4    False
Name: CustomerID, dtype: bool

In [ ]:
True + 1

2

In [ ]:
True + True

2

In [ ]:
True + False

1

In [ ]:
True - True

0

In [ ]:
df.loc[df['CustomerID'].isna()].head()

     InvoiceNo StockCode  ... CustomerID         Country
622     536414     22139  ...        NaN  United Kingdom
1443    536544     21773  ...        NaN  United Kingdom
1444    536544     21774  ...        NaN  United Kingdom
1445    536544     21786  ...        NaN  United Kingdom
1446    536544     21787  ...        NaN  United Kingdom

[5 rows x 8 columns]

In [ ]:
df.shape

(531285, 8)

---

#### 說明一下 pd.dropna()

In [ ]:
import numpy as np
import random

In [ ]:
w = np.random.randn(10, 4)

In [ ]:
w

array([[ 0.29608575,  1.28883013,  1.58660983, -0.00663779],
       [ 0.50345243, -0.1452337 , -1.03036709, -0.09508689],
       [-1.26308556,  0.62157059,  0.06909546, -1.21186079],
       [ 0.05986246, -2.4863298 ,  0.08305171,  0.84035422],
       [-0.44465499,  0.68139336, -0.73170164,  0.30719243],
       [ 1.51132145, -0.57943889,  0.25311822,  0.02203238],
       [-0.72201603,  0.68145348, -0.00252988,  0.04000014],
       [-0.08173901, -0.57751639,  0.64377125,  0.7520135 ],
       [ 0.8038636 , -0.65901263,  1.10212289, -0.34499177],
       [-1.12959909, -1.98119662,  1.45938752, -1.77223711]])

In [ ]:
for _ in range(5):
  x = random.randint(0, 9)
  y = random.randint(0, 3)
  w[x, y] = np.nan

In [ ]:
w

array([[ 0.29608575,         nan,  1.58660983, -0.00663779],
       [ 0.50345243, -0.1452337 ,         nan, -0.09508689],
       [-1.26308556,  0.62157059,  0.06909546, -1.21186079],
       [        nan, -2.4863298 ,  0.08305171,  0.84035422],
       [-0.44465499,  0.68139336, -0.73170164,  0.30719243],
       [ 1.51132145, -0.57943889,  0.25311822,  0.02203238],
       [-0.72201603,  0.68145348, -0.00252988,  0.04000014],
       [-0.08173901, -0.57751639,  0.64377125,  0.7520135 ],
       [ 0.8038636 , -0.65901263,         nan, -0.34499177],
       [-1.12959909, -1.98119662,         nan, -1.77223711]])

In [ ]:
dfw = pd.DataFrame(w)

In [ ]:
dfw

          0         1         2         3
0  0.296086       NaN  1.586610 -0.006638
1  0.503452 -0.145234       NaN -0.095087
2 -1.263086  0.621571  0.069095 -1.211861
3       NaN -2.486330  0.083052  0.840354
4 -0.444655  0.681393 -0.731702  0.307192
5  1.511321 -0.579439  0.253118  0.022032
6 -0.722016  0.681453 -0.002530  0.040000
7 -0.081739 -0.577516  0.643771  0.752014
8  0.803864 -0.659013       NaN -0.344992
9 -1.129599 -1.981197       NaN -1.772237

In [ ]:
dfw.dropna()

          0         1         2         3
2 -1.263086  0.621571  0.069095 -1.211861
4 -0.444655  0.681393 -0.731702  0.307192
5  1.511321 -0.579439  0.253118  0.022032
6 -0.722016  0.681453 -0.002530  0.040000
7 -0.081739 -0.577516  0.643771  0.752014

In [ ]:
dfw.dropna(subset=[0])

          0         1         2         3
0  0.296086       NaN  1.586610 -0.006638
1  0.503452 -0.145234       NaN -0.095087
2 -1.263086  0.621571  0.069095 -1.211861
4 -0.444655  0.681393 -0.731702  0.307192
5  1.511321 -0.579439  0.253118  0.022032
6 -0.722016  0.681453 -0.002530  0.040000
7 -0.081739 -0.577516  0.643771  0.752014
8  0.803864 -0.659013       NaN -0.344992
9 -1.129599 -1.981197       NaN -1.772237

---

In [ ]:
df = df.dropna(subset=['CustomerID'])

In [ ]:
df.shape

(397924, 8)

In [ ]:
df.head()

  InvoiceNo StockCode  ... CustomerID         Country
0    536365    85123A  ...    17850.0  United Kingdom
1    536365     71053  ...    17850.0  United Kingdom
2    536365    84406B  ...    17850.0  United Kingdom
3    536365    84029G  ...    17850.0  United Kingdom
4    536365    84029E  ...    17850.0  United Kingdom

[5 rows x 8 columns]

In [ ]:
customer_item_matrix = df.pivot_table(
    index='CustomerID', 
    columns='StockCode', 
    values='Quantity',
    aggfunc='sum'
)

In [ ]:
customer_item_matrix.head()

StockCode   10002  10080  10120  10125  10133  ...  C2  DOT   M  PADS  POST
CustomerID                                     ...
12346.0       NaN    NaN    NaN    NaN    NaN  ... NaN  NaN NaN   NaN   NaN
12347.0       NaN    NaN    NaN    NaN    NaN  ... NaN  NaN NaN   NaN   NaN
12348.0       NaN    NaN    NaN    NaN    NaN  ... NaN  NaN NaN   NaN   9.0
12349.0       NaN    NaN    NaN    NaN    NaN  ... NaN  NaN NaN   NaN   1.0
12350.0       NaN    NaN    NaN    NaN    NaN  ... NaN  NaN NaN   NaN   1.0

[5 rows x 3665 columns]

In [ ]:
customer_item_matrix.shape

(4339, 3665)

In [ ]:
df['StockCode'].nunique()

3665

In [ ]:
df['CustomerID'].nunique()

4339

In [ ]:
customer_item_matrix.loc[12348.0].sum()

2341.0

In [ ]:
customer_item_matrix = customer_item_matrix.applymap(lambda x: 1 if x > 0 else 0)

In [ ]:
customer_item_matrix.head()

StockCode   10002  10080  10120  10125  10133  ...  C2  DOT  M  PADS  POST
CustomerID                                     ...
12346.0         0      0      0      0      0  ...   0    0  0     0     0
12347.0         0      0      0      0      0  ...   0    0  0     0     0
12348.0         0      0      0      0      0  ...   0    0  0     0     1
12349.0         0      0      0      0      0  ...   0    0  0     0     1
12350.0         0      0      0      0      0  ...   0    0  0     0     1

[5 rows x 3665 columns]

# Collaborative Filtering

In [ ]:
from sklearn.metrics.pairwise import cosine_similarity

In [ ]:
user_user_sim_matrix = pd.DataFrame(
    cosine_similarity(customer_item_matrix)
)

In [ ]:
user_user_sim_matrix.head()

   0         1         2         3     ...  4335      4336      4337      4338
0   1.0  0.000000  0.000000  0.000000  ...   0.0  0.000000  0.000000  0.000000
1   0.0  1.000000  0.063022  0.046130  ...   0.0  0.113776  0.109364  0.012828
2   0.0  0.063022  1.000000  0.024953  ...   0.0  0.000000  0.170905  0.083269
3   0.0  0.046130  0.024953  1.000000  ...   0.0  0.067574  0.137124  0.030475
4   0.0  0.047795  0.051709  0.056773  ...   0.0  0.000000  0.044866  0.000000

[5 rows x 4339 columns]

In [ ]:
a = np.array([0, 1, 0, 1, 1, 0])
b = np.array([1, 1, 1, 1, 1, 1])

In [ ]:
nab = (a*b).sum()

In [ ]:
da = np.sqrt((a**2).sum())

In [ ]:
db = np.sqrt((b**2).sum())

In [ ]:
nab / (da*db)

0.7071067811865476

In [ ]:
user_user_sim_matrix.columns = customer_item_matrix.index
user_user_sim_matrix.index = customer_item_matrix.index

# user_user_sim_matrix['CustomerID'] = customer_item_matrix.index
# user_user_sim_matrix = user_user_sim_matrix.set_index('CustomerID')

In [ ]:
user_user_sim_matrix.head()

CustomerID  12346.0   12347.0   12348.0  ...   18282.0   18283.0   18287.0
CustomerID                               ...
12346.0         1.0  0.000000  0.000000  ...  0.000000  0.000000  0.000000
12347.0         0.0  1.000000  0.063022  ...  0.113776  0.109364  0.012828
12348.0         0.0  0.063022  1.000000  ...  0.000000  0.170905  0.083269
12349.0         0.0  0.046130  0.024953  ...  0.067574  0.137124  0.030475
12350.0         0.0  0.047795  0.051709  ...  0.000000  0.044866  0.000000

[5 rows x 4339 columns]

In [ ]:
user_user_sim_matrix.loc[12350.0].sort_values(ascending=False)

CustomerID
12350.0    1.000000
17935.0    0.183340
12414.0    0.181902
12652.0    0.175035
16692.0    0.171499
             ...
15953.0    0.000000
15952.0    0.000000
15951.0    0.000000
15950.0    0.000000
12346.0    0.000000
Name: 12350.0, Length: 4339, dtype: float64

In [ ]:
customer_item_matrix.loc[12350.0].nonzero()

AttributeError: ignored

In [ ]:
items_bought_by_A = set(customer_item_matrix.loc[12350.0][customer_item_matrix.loc[12350.0]==1].index)
items_bought_by_A

{20615,
 20652,
 21171,
 21832,
 21864,
 21866,
 21908,
 21915,
 22348,
 22412,
 22551,
 22557,
 22620,
 '79066K',
 '79191C',
 '84086C',
 'POST'}

In [ ]:
items_bought_by_B = set(customer_item_matrix.loc[17935.0][customer_item_matrix.loc[17935.0]==1].index)
items_bought_by_B

{20657,
 20659,
 20828,
 20856,
 21051,
 21866,
 21867,
 22208,
 22209,
 22210,
 22211,
 22449,
 22450,
 22551,
 22553,
 22557,
 22640,
 22659,
 22749,
 22752,
 22753,
 22754,
 22755,
 23290,
 23292,
 23309,
 '85099B',
 'POST'}

In [ ]:
items_to_recommend_to_B = items_bought_by_A - items_bought_by_B

In [ ]:
items_to_recommend_to_B

{20615,
 20652,
 21171,
 21832,
 21864,
 21908,
 21915,
 22348,
 22412,
 22620,
 '79066K',
 '79191C',
 '84086C'}

In [ ]:
df.loc[df['StockCode'].isin(items_to_recommend_to_B), 
    ['StockCode', 'Description']
].drop_duplicates().set_index('StockCode')

                               Description
StockCode
21832                 CHOCOLATE CALCULATOR
21915               RED  HARMONICA IN BOX
22620          4 TRADITIONAL SPINNING TOPS
79066K                      RETRO MOD TRAY
21864      UNION JACK FLAG PASSPORT COVER
79191C         RETRO PLASTIC ELEPHANT TRAY
21908        CHOCOLATE THIS WAY METAL SIGN
20615         BLUE POLKADOT PASSPORT COVER
20652           BLUE POLKADOT LUGGAGE TAG
22348          TEA BAG PLATE RED RETROSPOT
22412      METAL SIGN NEIGHBOURHOOD WITCH
21171                 BATHROOM METAL SIGN
84086C             PINK/PURPLE RETRO RADIO

# Item-based Collaborative Filtering

In [ ]:
item_item_sim_matrix = pd.DataFrame(cosine_similarity(customer_item_matrix.T))

In [ ]:
item_item_sim_matrix.columns = customer_item_matrix.T.index
item_item_sim_matrix.index = customer_item_matrix.T.index

In [ ]:
item_item_sim_matrix

StockCode     10002     10080     10120  ...         M      PADS      POST
StockCode                                ...
10002      1.000000  0.000000  0.094868  ...  0.066915  0.000000  0.078217
10080      0.000000  1.000000  0.000000  ...  0.016182  0.000000  0.000000
10120      0.094868  0.000000  1.000000  ...  0.070535  0.000000  0.010993
10125      0.090351  0.032774  0.057143  ...  0.070535  0.000000  0.070669
10133      0.062932  0.045655  0.059702  ...  0.070185  0.049752  0.021877
...             ...       ...       ...  ...       ...       ...       ...
C2         0.029361  0.000000  0.000000  ...  0.026196  0.000000  0.020413
DOT        0.000000  0.000000  0.000000  ...  0.000000  0.000000  0.000000
M          0.066915  0.016182  0.070535  ...  1.000000  0.000000  0.077539
PADS       0.000000  0.000000  0.000000  ...  0.000000  1.000000  0.000000
POST       0.078217  0.000000  0.010993  ...  0.077539  0.000000  1.000000

[3665 rows x 3665 columns]

In [ ]:
top_10_similar_items = list(
    item_item_sim_matrix\
        .loc[23166]\
        .sort_values(ascending=False)\
        .iloc[:10]\
    .index
)

In [ ]:
top_10_similar_items

[23166, 23165, 23167, 22993, 23307, 22722, 22720, 22666, 23243, 22961]

In [ ]:
df.loc[
    df['StockCode'].isin(top_10_similar_items), 
    ['StockCode', 'Description']
].drop_duplicates().set_index('StockCode').loc[top_10_similar_items]

                                   Description
StockCode
23166           MEDIUM CERAMIC TOP STORAGE JAR
23165            LARGE CERAMIC TOP STORAGE JAR
23167           SMALL CERAMIC TOP STORAGE JAR
22993             SET OF 4 PANTRY JELLY MOULDS
23307      SET OF 60 PANTRY DESIGN CAKE CASES
22722        SET OF 6 SPICE TINS PANTRY DESIGN
22720        SET OF 3 CAKE TINS PANTRY DESIGN
22666          RECIPE BOX PANTRY YELLOW DESIGN
23243      SET OF TEA COFFEE SUGAR TINS PANTRY
22961                   JAM MAKING SET PRINTED